#!/bin/bash

# build TAGS file
#rm TAGS
#find . -name '*.c' -print -or -name "*.h" -print | grep -v ccls | grep -v examples | xargs etags --append

cc="gcc"
# FIXME: don't ignore warnings
flags="-g -w"

# build x86 binaries

# build preprocessor
$cc -m32 $flags -DSTANDALONE parse.c lex.c pre.c -o bin/pre
# build ast generator
$cc -m32 $flags main-ast.c lex.c ast.c pre.c parse.c -o bin/ast
# build compiler
$cc -m32 $flags main.c lex.c ast.c x86.c pe.c elf.c pre.c parse.c memory.c -o bin/ocean

# build x64 binaries

$cc -m64 $flags -DSTANDALONE parse.c lex.c pre.c -o bin/pre64
# build ast generator
$cc -m64 $flags main-ast.c lex.c ast.c pre.c parse.c -o bin/ast64
# build compiler
$cc -m64 $flags main.c lex.c ast.c x86.c pe.c elf.c pre.c parse.c memory.c -o bin/ocean64
