#!/bin/bash

# build TAGS file
#rm TAGS
#find . -name '*.c' -print -or -name "*.h" -print | grep -v ccls | grep -v examples | xargs etags --append

cc="i686-w64-mingw32-gcc"
# FIXME: don't ignore warnings
flags="-g -w"

# build preprocessor
$cc -m32 $flags -DSTANDALONE parse.c lex.c pre.c -o bin/pre.exe
# build ast generator
$cc -m32 $flags main-ast.c lex.c ast.c pre.c parse.c -o bin/ast.exe
# build compiler
$cc -m32 $flags main.c lex.c ast.c x86.c pe.c elf.c pre.c parse.c memory.c -o bin/ocean.exe
